# Generated by Django 5.0 on 2023-12-20 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadUser', '0002_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Usuarios',
        ),
    ]
