# Generated by Django 5.0 on 2023-12-20 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadUser', '0003_rename_usuario_usuarios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
